---
# tasks file for jenkins
- name: install jdk
  apt: name=java-1.8.0-openjdk-devel state=present

- name: add jenkins to repo
  apt_repository: repo='http://pkg.jenkins-ci.org/debian binary/' state=present

- name: import apt key
  apt_key: url=http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key state=present

- name: install jenkins
  apt: name=jenkins state=present

- name: start jenkins
  service: name=jenkins state=started enabled=yes
